server:
  port: 8004

spring:
  application:
    name: mcp-client
  ai:
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 60s
        type: SYNC
        streamable-http:
          connections:
            weather-streamable:
              url: http://127.0.0.1:8003
              endpoint: /api/mcp
